export const EMPLOYEE = {
  GET_EMPLOYEES: 'GET_EMPLOYEES',
  GET_EMPLOYEE_BY_ID: 'GET_EMPLOYEE_BY_ID',
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  SEARCH_EMPLOYEE: 'SEARCH_EMPLOYEE',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE'
};

export const CERTIFICATE = {
  GET_CERTIFICATES: 'GET_CERTIFICATE_BY_ID_EMPLOYEE',
  GET_CERTIFICATE_BY_ID: 'GET_CERTIFICATE_BY_ID',
  CREATE_CERTIFICATE: 'CREATE_CERTIFICATE',
  UPDATE_CERTIFICATE: 'UPDATE_CERTIFICATE',
  DELETE_CERTIFICATE: 'DELETE_CERTIFICATE'
};

export const FAMILY = {
  GET_FAMILY: 'GET_FAMILY_BY_ID_EMPLOYEE',
  GET_FAMILY_BY_ID: 'GET_FAMILY_BY_ID',
  CREATE_FAMILY_MEMBER: 'CREATE_FAMILY_MEMBER',
  UPDATE_FAMILY: 'UPDATE_FAMILY',
  DELETE_FAMILY_MEMBER: 'DELETE_FAMILY_MEMBER'
};

export const EXPERIENCE = {
  GET_EXPERIENCES: 'GET_EXPERIENCES_BY_ID_EMPLOYEE',
  GET_EXPERIENCE_BY_ID: 'GET_EXPERIENCE_BY_ID',
  CREATE_EXPERIENCE: 'CREATE_EXPERIENCE',
  UPDATE_EXPERIENCE: 'UPDATE_EXPERIENCE',
  DELETE_EXPERIENCE: 'DELETE_EXPERIENCE'
};

export const SALARY = {
  GET_SALARYS: 'GET_SALARYS_BY_ID_EMPLOYEE',
  GET_SALARYS_BY_LEADER: 'GET_SALARYS_BY_LEADER',
  GET_SALARY_BY_ID: 'GET_SALARY_BY_ID',
  CREATE_SALARY: 'CREATE_SALARY',
  UPDATE_SALARY: 'UPDATE_SALARY',
  DELETE_SALARY: 'DELETE_SALARY'
};

export const PROCESS = {
  GET_PROCESS_LIST: 'GET_PROCESS_LIST_BY_ID_EMPLOYEE',
  GET_PROCESS_LIST_BY_LEADER: 'GET_PROCESS_LIST_BY_LEADER',
  GET_PROCESS_BY_ID: 'GET_PROCESS_BY_ID',
  CREATE_PROCESS: 'CREATE_PROCESS',
  UPDATE_PROCESS: 'UPDATE_PROCESS',
  DELETE_PROCESS: 'DELETE_PROCESS'
};

export const PROPOSAL = {
  GET_PROPOSALS: 'GET_PROPOSALS_BY_ID_EMPLOYEE',
  GET_PROPOSALS_BY_LEADER: 'GET_PROPOSALS_BY_LEADER',
  GET_PROPOSAL_BY_ID: 'GET_PROPOSAL_BY_ID',
  CREATE_PROPOSAL: 'CREATE_PROPOSAL',
  UPDATE_PROPOSAL: 'UPDATE_PROPOSAL',
  DELETE_PROPOSAL: 'DELETE_PROPOSAL'
};